// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Feed struct {
	ID            int64
	Url           string
	Title         sql.NullString
	LastFetchedAt sql.NullTime
	CreatedAt     time.Time
}

type SchemaMigrations struct {
	Version string
}
